### ISSUE TITLE
no Sound

### ISSUE THREAD

**Issue by kytv76** [fivebanger/kodi_addons#10]
Hi,
any radio channel is playing in Kodi 21 on Debian Bookworm.
With the radio.de-light plugin it works.
Any idea?

**Comment by fivebanger** [comment]
Without a log file its impossible and just guessing...

**Comment by kytv76** [comment]
That is what the log says:
EXCEPTION Thrown (PythonToCppException) : -->Python callback/scri
pt returned the following error<--
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'KeyError'>
Error Contents: 'item_id'
Traceback (most recent call last):
File "/home/kodi/.kodi/addons/plugin.video.jellycon/resources/lib
/play_utils.py", line 1347, in onPlayBackStarted
jellyfin_item_id = play_data["item_id"]
~~~~~~~~~^^^^^^^^^^^
KeyError: 'item_id'
-->End of Python script error report<--
It looks like the plugin starts the jellycon player which won't work.
How can I change this?

**Comment by fivebanger** [comment]
Sorry, but I have no idea why this exception is thrown. The exception is thrown from plugin `plugin.video.jellycon`. The Radio.de addon has no dependencies to something like `plugin.video.jellycon`. I have never seen this addon or have installed that addon on one of my systems, I even don't know what this addon is doing. 

The Radio.de addon simply extracts the station's stream url from the radio.net website and passes it to Kodi, using a Kodi-like manner (like many other addons doing). At the end it calls `xbmcplugin.setResolvedUrl()` and that's it. 

No idea how this triggers the jellycon addon.

**Comment by fivebanger** [comment]
Maybe that issue is something that should be reported in the respective jellycon forum. In case this addon relies on keys provided by other addons, the jellycon addon should carefully check if those keys are provided or not. The addon that triggers jellycon (Radio.de in that case) does not know what jellycon needs and how to provide.

**Comment by fivebanger** [comment]
Closed since not a Radio.de addon issue.
