### ISSUE TITLE
Radio.de M3U format or Station Add?

### ISSUE THREAD

**Issue by insaneaux** [fivebanger/kodi_addons#6]
Hey, thanks for this addon, works well. I have been looking for a way to add a station I was able to sniff out from Audacy. I have tried to upload a basic M3U that works in VLC but isn't recognized in the addon. I also see where editing the stations.jsn file would do it but I cannot find that file anywhere in the addon (using plugin.audio.radiode/plugin.audio.radiode-1.1.3.zip).

I am trying to add https://live.amperwave.net/direct/audacy-wwlamaac-imc&error=ok

Any help is appreciated. Thanks again for all your work!

**Comment by fivebanger** [comment]
The "stations.jsn" file is located under ../userdata/addon_data/plugin.audio.radiode/.radiode. Depending on the OS you are running Kodi on you have to check where Kodi is installed. The "/.radiode" folder is a hidden folder, maybe you have to turn on "show hidden files" in your file explorer. 

If this folder does not exists yet in your "/user_date/addon_data" directory you have to add a station initially from the "Radio.de" addon. Anny station works fine, you can delete it later on. It's just to create a "stations.jsn" file once.

Within the stations.jsn file, pls. add this line or modify an existing one:

`{"data": {"id": "", "name": "Custom Station", "icon_url": "", "stream_url": "https://live.amperwave.net/direct/audacy-wwlamaac-imc&error=ok"}, "mode": "play_stream"}`

Customize the "name" field and the "icon_url" to your liking.

**Comment by fivebanger** [comment]
You can also use "Import station from m3u file" from the addon settings. Create a file "my-stations.m3u" and paste in the following lines:

```
#EXTM3U
#EXTINF:-1 tvg-name="Custom Station" tvg-radio="true" tvg-logo="",Custom Station
https://live.amperwave.net/direct/audacy-wwlamaac-imc&error=ok
```

That's the format used for exporting a station to an existing m3u file, therefore this format should be used for importing as well.

**Comment by insaneaux** [comment]
Done thanks!
Works great as well.

Just a quick question: Is there a way to label the stream in the upper right-hand corner, if possible?

![image](https://github.com/user-attachments/assets/497dd89b-110e-43ed-961e-ad8a14514e3c)

**Comment by insaneaux** [comment]
Good to close.
